Repository Vizzuality/amazonia-360, pull requests merged in 2025-09, with the labels that each got.

#218 Remove raster tiler
  api/src/app/config.py
  api/src/app/main.py
  api/src/app/models/zonal_stats.py
  api/src/app/routers/zonal_stats.py
  api/tests/conftest.py
  api/tests/scripts/test_csv_to_tiles.py
  api/tests/test_main.py
  api/tests/test_zonal_stats.py
Labels: API

#214 feat: webshot widget screenshots
  client/src/app/[locale]/(app)/error.tsx
  client/src/app/[locale]/(app)/hub/page.tsx
  client/src/app/[locale]/(app)/indicators/page.tsx
  client/src/app/[locale]/(app)/layout.tsx
  client/src/app/[locale]/(app)/not-found.tsx
  client/src/app/[locale]/(app)/page.tsx
  client/src/app/[locale]/(app)/report/(new)/grid/page.tsx
  client/src/app/[locale]/(app)/report/(new)/indicators/page.tsx
  client/src/app/[locale]/(app)/report/(new)/layout.tsx
  client/src/app/[locale]/(app)/report/(new)/page.tsx
  client/src/app/[locale]/(app)/report/(results)/results/loading.tsx
  client/src/app/[locale]/(app)/report/(results)/results/page.tsx
  client/src/app/[locale]/(app)/report/layout.tsx
  client/src/app/[locale]/layout.tsx
  client/src/app/[locale]/webshot/layout.tsx
  client/src/app/[locale]/webshot/widgets/[id]/[type]/page.tsx
  client/src/constants/webshot.ts
  client/src/containers/card/index.tsx
  client/src/containers/results/content/indicators/card.tsx
  client/src/containers/webshot/webshot-widget-container.tsx
  webshot/src/widgets/widgets.service.ts
Labels: front

#213 JSON indicators test v26 08 2025
  client/datum/indicators.json
Labels: Data Update

#222 Bug: correct texts in home page
  client/src/containers/home/key-features-grid/cards-container.tsx
  client/src/i18n/translations/es.json
Labels: bug, front

#223 Bug: Publication icon
  client/src/containers/results/content/other-resources/resource.tsx
Labels: bug, front

#225 Grid: units
  client/src/containers/report/grid/desktop.tsx
  client/src/containers/report/grid/filters/search.tsx
  client/src/containers/report/grid/table/index.tsx
  client/src/containers/results/content/summary.tsx
  client/src/lib/indicators.ts
  client/src/styles/globals.css
Labels: enhancement, front

#228 Indicators controls
  client/src/app/store.ts
  client/src/containers/report/indicators/footer/index.tsx
  client/src/containers/report/indicators/topics/item.tsx
Labels: enhancement, front

#238 Fix mosaic selector labels
  client/src/containers/home/constants.tsx
Labels: front

#235 Third party
  client/src/app/[locale]/(app)/layout.tsx
  client/src/containers/third-party/index.tsx
  client/src/i18n/translations/en.json
  client/src/i18n/translations/es.json
  client/src/i18n/translations/pt.json
Labels: enhancement, front

#239 Improve h3 tile rendering perfomance
  client/src/containers/report/map/layer-manager/grid-layer.tsx
Labels: front
